setwd(normalizePath(dirname(R.utils::commandArgs(asValues=TRUE)$"f")))
source("../../scripts/h2o-r-test-setup.R")


test.seed.string <- function() {
    data <- h2o.importFile(path = locate('smalldata/iris/iris.csv'))
    names(data)[5]<-paste("Species")
    df <- as.h2o(data)

    # Set parameters
    params                      <- list()
    params$y                    <- "Species"
    params$training_frame       <- df
    params$ntrees               <- 3
    params$score_each_iteration <- TRUE

    # Get autogenerated seed as string, it could not be string by default
    gbm_model1 <- do.call(h2o.gbm, params)
    
    rmse1 <- gbm_model1@model$scoring_history$training_rmse
    logloss1 <- gbm_model1@model$scoring_history$training_logloss

    # Train model with string seed
    params$seed <- gbm_model1@parameters$seed_string
    gbm_model2 <- do.call(h2o.gbm, params)
    rmse2 <- gbm_model2@model$scoring_history$training_rmse
    logloss2 <- gbm_model2@model$scoring_history$training_logloss

    # Compare results with same string seed setting autogenerated from h2o server
    expect_equal(gbm_model1@parameters$seed_string, gbm_model2@parameters$seed_string)
    expect_equal(rmse1, rmse2)
    expect_equal(logloss1, logloss2)

    # Expect warning when using long number in R
    params$seed <- -8664354335142703762
    expect_warning(do.call(h2o.gbm, params))

    drf_model <- do.call(h2o.drf, params)
    drf_model$seed_stringdata <- h2o.importFile(path = locate('smalldata/iris/iris.csv'))
    names(data)[5]<-paste("Species")
    df <- as.h2o(data)

    # Set parameters
    params                      <- list()
    params$y                    <- "Species"
    params$training_frame       <- df
    params$ntrees               <- 3
    params$score_each_iteration <- TRUE

    # Get autogenerated seed as string, it could not be string by default
    gbm_model1 <- do.call(h2o.gbm, params)
    
    rmse1 <- gbm_model1@model$scoring_history$training_rmse
    logloss1 <- gbm_model1@model$scoring_history$training_logloss

    # Train model with string seed
    params$seed <- gbm_model1@parameters$seed_string
    gbm_model2 <- do.call(h2o.gbm, params)
    rmse2 <- gbm_model2@model$scoring_history$training_rmse
    logloss2 <- gbm_model2@model$scoring_history$training_logloss

    # Compare results with same string seed setting autogenerated from h2o server
    expect_equal(gbm_model1@parameters$seed_string, gbm_model2@parameters$seed_string)
    expect_equal(rmse1, rmse2)
    expect_equal(logloss1, logloss2)

    # Expect warning when using long number in R
    params$seed <- -8664354335142703762
    expect_warning(do.call(h2o.gbm, params))

    drf_model <- do.call(h2o.randomForest, params)
    drf_model$seed_string
}

doTest("Test seed long vs. string", test.seed.string)
